#1.端口号配置
server:
  port: 8083
#2.整合mysql数据库
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gg? useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: fkyourdogss22
  #3.日期格式调整
  mvc:
    format:
      date: YYYY-MM-DD
# 整合mybatis
mybatis:
  mapper-locations: classpath:mappers/*.xml
